import prisma from "./prisma";

async function main() {
  // 브랜드 데이터 추가
  await prisma.brand.createMany({
    data: [
      { name: "에버블룸" },
      { name: "블루허브" },
      { name: "루나화이트" },
      { name: "네이처소울" },
      { name: "그린필드" },
      { name: "퓨어딥" },
      { name: "아쿠아하이드" },
      { name: "로지스킨" },
      { name: "피토베라" },
      { name: "오가닉테라" },
    ],
  });

  await prisma.product.createMany({
    data: [
      {
        name: "에버블룸 수분크림 50ml",
        productCode: "PRD1001",
        brandId: 2,
        price: 28000,
        stockQuantity: 100,
        thumbnailImageUrl: "",
        detailDescription: "피부 깊숙이 수분을 채워주는 고보습 크림",
        isSample: false,
        samplePrice: 1000,
      },
      {
        name: "에버블룸 클렌징폼",
        productCode: "PRD1002",
        brandId: 2,
        price: 15000,
        stockQuantity: 150,
        thumbnailImageUrl: "",
        detailDescription: "자극 없이 세정력 좋은 클렌징폼",
        isSample: true,
        samplePrice: 500,
      },
      {
        name: "블루허브 토너 150ml",
        productCode: "PRD1003",
        brandId: 3,
        price: 22000,
        stockQuantity: 80,
        thumbnailImageUrl: "",
        detailDescription: "피부를 진정시키는 천연 허브 토너",
        isSample: false,
        samplePrice: 900,
      },
      {
        name: "블루허브 미스트",
        productCode: "PRD1004",
        brandId: 3,
        price: 18000,
        stockQuantity: 200,
        thumbnailImageUrl: "",
        detailDescription: "휴대용 수분 공급 미스트",
        isSample: true,
        samplePrice: 600,
      },
      {
        name: "루나화이트 선크림 SPF50+",
        productCode: "PRD1005",
        brandId: 4,
        price: 24000,
        stockQuantity: 130,
        thumbnailImageUrl: "",
        detailDescription: "백탁 없이 산뜻한 선케어",
        isSample: false,
        samplePrice: 800,
      },
      {
        name: "루나화이트 톤업크림",
        productCode: "PRD1006",
        brandId: 4,
        price: 26000,
        stockQuantity: 120,
        thumbnailImageUrl: "",
        detailDescription: "자연스럽게 피부 톤을 밝혀주는 크림",
        isSample: true,
        samplePrice: 900,
      },
      {
        name: "네이처소울 에센스",
        productCode: "PRD1007",
        brandId: 5,
        price: 32000,
        stockQuantity: 70,
        thumbnailImageUrl: "",
        detailDescription: "탄력과 광채를 부여하는 집중 에센스",
        isSample: false,
        samplePrice: 1200,
      },
      {
        name: "네이처소울 아이크림",
        productCode: "PRD1008",
        brandId: 5,
        price: 35000,
        stockQuantity: 60,
        thumbnailImageUrl: "",
        detailDescription: "눈가 주름을 완화하는 아이크림",
        isSample: true,
        samplePrice: 1000,
      },
      {
        name: "그린필드 바디로션",
        productCode: "PRD1009",
        brandId: 6,
        price: 20000,
        stockQuantity: 90,
        thumbnailImageUrl: "",
        detailDescription: "피부를 부드럽게 감싸는 보디로션",
        isSample: false,
        samplePrice: 700,
      },
      {
        name: "그린필드 샴푸",
        productCode: "PRD1010",
        brandId: 6,
        price: 19000,
        stockQuantity: 110,
        thumbnailImageUrl: "",
        detailDescription: "두피 건강을 위한 자연유래 샴푸",
        isSample: true,
        samplePrice: 600,
      },
      {
        name: "퓨어딥 클렌징 오일",
        productCode: "PRD1011",
        brandId: 7,
        price: 27000,
        stockQuantity: 100,
        thumbnailImageUrl: "",
        detailDescription: "워터프루프 메이크업까지 말끔히 제거",
        isSample: false,
        samplePrice: 900,
      },
      {
        name: "퓨어딥 립앤아이 리무버",
        productCode: "PRD1012",
        brandId: 7,
        price: 14000,
        stockQuantity: 150,
        thumbnailImageUrl: "",
        detailDescription: "눈가에 자극 없는 리무버",
        isSample: true,
        samplePrice: 500,
      },
      {
        name: "아쿠아하이드 앰플",
        productCode: "PRD1013",
        brandId: 8,
        price: 30000,
        stockQuantity: 90,
        thumbnailImageUrl: "",
        detailDescription: "극건성 피부를 위한 수분 앰플",
        isSample: false,
        samplePrice: 1100,
      },
      {
        name: "아쿠아하이드 마스크팩",
        productCode: "PRD1014",
        brandId: 8,
        price: 2500,
        stockQuantity: 300,
        thumbnailImageUrl: "",
        detailDescription: "수분 폭탄 마스크 한 장",
        isSample: true,
        samplePrice: 500,
      },
      {
        name: "로지스킨 필링젤",
        productCode: "PRD1015",
        brandId: 9,
        price: 23000,
        stockQuantity: 95,
        thumbnailImageUrl: "",
        detailDescription: "묵은 각질을 부드럽게 제거",
        isSample: false,
        samplePrice: 800,
      },
      {
        name: "로지스킨 핸드크림",
        productCode: "PRD1016",
        brandId: 9,
        price: 12000,
        stockQuantity: 200,
        thumbnailImageUrl: "",
        detailDescription: "장미 향기 가득한 보습 핸드크림",
        isSample: true,
        samplePrice: 400,
      },
      {
        name: "피토베라 수딩젤",
        productCode: "PRD1017",
        brandId: 10,
        price: 17000,
        stockQuantity: 100,
        thumbnailImageUrl: "",
        detailDescription: "자극받은 피부를 진정시켜주는 젤",
        isSample: false,
        samplePrice: 700,
      },
      {
        name: "피토베라 시카크림",
        productCode: "PRD1018",
        brandId: 10,
        price: 27000,
        stockQuantity: 100,
        thumbnailImageUrl: "",
        detailDescription: "트러블 케어에 효과적인 시카크림",
        isSample: true,
        samplePrice: 900,
      },
      {
        name: "오가닉테라 스킨토너",
        productCode: "PRD1019",
        brandId: 11,
        price: 21000,
        stockQuantity: 120,
        thumbnailImageUrl: "",
        detailDescription: "유기농 원료로 만든 순한 토너",
        isSample: false,
        samplePrice: 800,
      },
      {
        name: "오가닉테라 클렌징밤",
        productCode: "PRD1020",
        brandId: 11,
        price: 26000,
        stockQuantity: 90,
        thumbnailImageUrl: "",
        detailDescription: "딥클렌징용 클렌징 밤",
        isSample: true,
        samplePrice: 950,
      },
    ],
  });
}

main()
  .then(() => {
    console.log("✅ 상품 데이터 시딩 완료!");
  })
  .catch((e) => {
    console.error("❌ 시딩 에러:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
